import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  scrollContent: { paddingBottom: 24 },
  banner: { width: '100%', height: 200, marginTop: 25, borderTopLeftRadius: 30, borderTopRightRadius: 30 },
  card: {
    marginHorizontal: 20,
    marginTop: 16,
    padding: 14,
  },
  companyTitle: { color: '#444444', fontSize: 14},
  infoRow: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  infoText: { marginLeft: 12, color: '#444444', fontSize: 12 },
  sectionHead: { marginHorizontal: 20, marginTop: 24 },
  sectionTitle: { color: '#1D3A70', fontSize: 14, fontWeight: '600' },
  sectionSub: { color: '#444444', fontSize: 12, marginTop: 4 },
  featuresRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: 20,
    marginTop: 16,
    gap: 8,
    justifyContent: 'center',
  },
  featureCard: {
    flex: 1,
    minWidth: 105,
    maxWidth: 125,
    borderWidth: 1,
    borderColor: '#EFF0F3',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    paddingVertical: 11,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  featureIconWrap: { width: 48, height: 48, borderRadius: 6, backgroundColor: '#EFF0F3', alignItems: 'center', justifyContent: 'center' },
  featureTitle: { color: '#1D3A70', fontSize: 12, fontWeight: '500', textAlign: 'center', marginTop: 10, lineHeight: 16 },
  ctaWrap: { marginHorizontal: 20, marginTop: 16 },
  ctaButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#099453', borderRadius: 12, paddingVertical: 15 },
  ctaButtonDisabled: { backgroundColor: '#CCCCCC' },
  ctaText: { marginLeft: 8, color: '#FFFFFF', fontSize: 14, fontWeight: '500' },
  noCatalogText: { color: '#E53E3E', fontSize: 12, textAlign: 'center', marginTop: 8 },
  tabsHeader: { flexDirection: 'row', alignItems: 'center', marginTop: 24, paddingHorizontal: 20, backgroundColor: '#F8F8FB' },
  tabLabelWrap: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  tabTitle: { color: '#444444', fontSize: 14, marginVertical: 14  },
  tabInactive: { color: '#DDDDDD' },
  underlineBar: {  backgroundColor: '#099453', width: 175, height: 3 },
  tabDivider: { width: 1, height: '60%', backgroundColor: '#DDDDDD' },
  productsList: { paddingHorizontal: 20, paddingTop: 8 },
  productItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 10, borderBottomWidth: 1, borderBottomColor: '#EEEEEE' },
  productIcon: { width: 28, height: 28, marginRight: 12 },
  productText: { color: '#404040', fontSize: 14 },
});
