import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  headerTitle: {
    fontSize: 18,
    color: '#101010',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 100,
  },
  subtitle: {
    fontSize: 15,
    color: '#404040',
    textAlign: 'center',
    marginBottom: 24,
  },
  fieldsContainer: {
    paddingHorizontal: 0,
  },
  fieldContainer: {
    marginBottom: 24,
  },
  mainCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 24,
    shadowColor: '#6d6d6d',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  fieldContainerInCard: {
    marginBottom: 0,
  },
  cardDivider: {
    height: 1,
    backgroundColor: '#ddd',
    marginVertical: 20,
  },
  label: {
    fontFamily: 'Poppins-Medium',
    fontSize: 13,
    color: '#444',
    marginBottom: 8,
  },
  required: {
    color: '#f32735',
  },
  dropdown: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    paddingVertical: 12,
  },
  dropdownText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    color: '#404040',
    letterSpacing: 0.3,
  },
  dropdownPlaceholder: {
    color: '#bcbcbc',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  dropdownModal: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    paddingTop: 24,
    paddingBottom: 40,
    shadowColor: '#6d6d6d',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalPlaceholder: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#898a8d',
    paddingHorizontal: 40,
    paddingVertical: 16,
  },
  dropdownItem: {
    paddingHorizontal: 40,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  dropdownItemText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#404040',
    letterSpacing: 0.3,
  },
  inputTypeModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  inputTypeModal: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    height: 495,
    shadowColor: '#6d6d6d',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalCloseButton: {
    position: 'absolute',
    top: -20,
    right: 0,
    width: 41,
    height: 41,
    borderRadius: 20.5,
    backgroundColor: '#EDEDED',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 40,
    marginTop: 30,
    marginBottom: 16,
    paddingHorizontal: 16,
    height: 46,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  searchInput: {
    flex: 1,
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    color: '#404040',
    marginLeft: 12,
  },
  itemsList: {
    flex: 1,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 40,
    paddingVertical: 16,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#404040',
  },
  itemCategory: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#898a8d',
    marginTop: 4,
  },
  itemUnit: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#898a8d',
  },
  itemPricing: {
    alignItems: 'flex-end',
  },
  itemPrice: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#404040',
    marginBottom: 8,
  },
  addButton: {
    backgroundColor: '#ededed',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 5,
  },
  addButtonText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#099453',
  },
  itemDivider: {
    height: 1,
    backgroundColor: '#ddd',
    marginHorizontal: 40,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    flexDirection: 'column',
    gap: 10,
    paddingHorizontal: 24,
    paddingVertical: 14,
    shadowColor: '#6d6d6d',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  bottomBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 0,
  },
  cartInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cartInfoRow: {
    flex: 1,
    flexShrink: 1,
    marginRight: 12,
  },
  cartIconBottom: {
    fontSize: 20,
  },
  cartAmount: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#404040',
  },
  dividerVertical: {
    width: 1,
    height: 31,
    backgroundColor: '#ddd',
  },
  cartItemCount: {
    flexShrink: 1,
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#898a8d',
  },
  viewCartButton: {
    backgroundColor: '#099453',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
  },
  viewCartButtonRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 5,
    alignItems: undefined,
  },
  viewCartButtonDisabled: {
    backgroundColor: '#ededed',
    opacity: 0.5,
  },
  viewCartText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#fff',
  },
  viewCartTextDisabled: {
    color: '#099453',
  },
  addedItemSection: {
    marginTop: 8,
  },
  addedItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  addedItemName: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#404040',
  },
  trashIcon: {
    fontSize: 18,
    color: '#898a8d',
    padding: 4,
  },
  addedItemDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  addedItemPrice: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#404040',
  },
  addedItemUnit: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#898a8d',
  },
  quantityRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  quantityControl: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  quantityButton: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    width: 31,
    height: 31,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityButtonLeft: {
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
  },
  quantityButtonRight: {
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
  },
  quantityButtonText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#404040',
  },
  quantityDisplay: {
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#ddd',
    width: 31,
    height: 31,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#404040',
  },
  cardTotalSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cartIconText: {
    fontSize: 18,
  },
  cardTotalAmount: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#404040',
  },
  cardTotalDivider: {
    width: 1,
    height: 16,
    backgroundColor: '#ddd',
  },
  cardTotalItems: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#898a8d',
  },
  addAnotherButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
    marginBottom: 24,
  },
  addAnotherIcon: {
    backgroundColor: '#099453',
    borderRadius: 3,
    width: 19,
    height: 19,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addAnotherIconText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
  },
  addAnotherText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#3b74ba',
    textDecorationLine: 'underline',
  },
});
