import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#fff',
  },
  headerTitle: {
    fontSize: 14,
    color: '#000',
    letterSpacing: 0.3,
  },
  scrollContent: {
    paddingHorizontal: 10,
    paddingTop: 14,
    paddingBottom: 100,
  },
  mainCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
    paddingTop: 20,
    paddingBottom: 270,
    marginBottom: 0,
  },
  tableHeader: {
    flexDirection: 'row',
    position: 'relative',
    paddingHorizontal: 0,
    marginBottom: 12,
    height: 12,
  },
  tableHeaderText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#404040',
    textTransform: 'uppercase',
    lineHeight: 12,
    position: 'absolute',
  },
  colItems: {
    left: 20,
  },
  colPrice: {
    left: 142,
  },
  colQty: {
    left: 213,
  },
  colTotal: {
    left: 297,
  },
  divider: {
    height: 1,
    backgroundColor: '#ddd',
    marginBottom: 12,
  },
  itemRow: {
    flexDirection: 'row',
    position: 'relative',
    paddingHorizontal: 0,
    marginBottom: 8,
    minHeight: 30,
  },
  itemCategory: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#8b8b8b',
    letterSpacing: 0.3,
    lineHeight: 15,
    marginLeft: 20,
    width: 110,
  },
  itemActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  actionText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 10,
    color: '#8b8b8b',
    lineHeight: 12,
  },
  actionDivider: {
    width: 1,
    height: 16,
    backgroundColor: '#ddd',
    marginHorizontal: 16,
  },
  itemPrice: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#8b8b8b',
    letterSpacing: 0.3,
    lineHeight: 15,
    position: 'absolute',
    left: 142,
    top: 0,
  },
  qtyBadge: {
    backgroundColor: '#d9d9d9',
    borderRadius: 3,
    paddingHorizontal: 8,
    paddingVertical: 3,
    minWidth: 45,
    maxWidth: 88,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    left: 204,
    top: -2,
    overflow: 'hidden',
  },
  qtyBadgeText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#8b8b8b',
    letterSpacing: 0.3,
    lineHeight: 15,
    textAlign: 'center',
  },
  itemTotal: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#8b8b8b',
    letterSpacing: 0.3,
    lineHeight: 15,
    position: 'absolute',
    left: 296,
    top: 0,
  },
  detailsCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
    marginTop: -254,
    marginHorizontal: 15,
    marginBottom: 16,
    overflow: 'hidden',
  },
  detailsTab: {
    backgroundColor: '#099453',
    paddingVertical: 4,
    paddingHorizontal: 40,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    alignItems: 'center',
    alignSelf: 'center',
    width: 200,
  },
  detailsTabText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#fff',
    lineHeight: 12,
  },
  detailsContent: {
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 0,
    lineHeight: 27,
  },
  detailLabel: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: 'rgba(47, 43, 61, 0.7)',
    lineHeight: 27,
  },
  detailValue: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: 'rgba(47, 43, 61, 0.7)',
    lineHeight: 27,
  },
  detailsDivider: {
    height: 1,
    backgroundColor: '#ddd',
    marginHorizontal: 15,
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 40,
    paddingVertical: 20,
    backgroundColor: '#fff',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderRadius: 20,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  modalTitle: {
    fontSize: 18,
    color: '#000',
  },
  modalCloseButton: {
    fontSize: 16,
    color: '#666',
    fontWeight: '300',
    lineHeight: 16,
  },
  modalContent: {
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  modalDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  modalDetailRowLast: {
    borderBottomWidth: 0,
  },
  modalDetailLabel: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    color: 'rgba(47, 43, 61, 0.7)',
    flex: 1,
  },
  modalDetailValue: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#000',
    flex: 1,
    textAlign: 'right',
  },
  modalDetailTotal: {
    fontSize: 16,
    color: '#099453',
  },
  modalFooter: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 10,
  },
  modalCloseButtonBottom: {
    backgroundColor: '#099453',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    minWidth: 100,
  },
  modalCloseButtonText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#fff',
  },
});
