import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#fff',
  },
  headerTitle: {
    fontSize: 14,
    color: '#000',
    letterSpacing: 0.3,
  },
  scrollContent: {
    paddingHorizontal: 10,
    paddingTop: 14,
    paddingBottom: 40,
  },
  invoiceCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
    paddingTop: 24,
    paddingBottom: 24,
    marginBottom: 32,
  },
  invoiceInfo: {
    paddingHorizontal: 30,
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    lineHeight: 27,
  },
  infoLabel: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: 'rgba(47, 43, 61, 0.7)',
    lineHeight: 27,
  },
  infoValue: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: 'rgba(47, 43, 61, 0.7)',
    textAlign: 'right',
    lineHeight: 27,
  },
  itemsTable: {
    paddingHorizontal: 15,
  },
  tableHeader: {
    backgroundColor: '#606060',
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 12,
  },
  tableHeaderText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 10,
    color: '#fff',
    textTransform: 'uppercase',
  },
  colHash: {
    width: 25,
  },
  colItemsHeader: {
    flex: 1.5,
  },
  colPriceHeader: {
    flex: 1,
    textAlign: 'center',
  },
  colQtyHeader: {
    flex: 1,
    textAlign: 'center',
  },
  colTotalHeader: {
    flex: 1,
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tableCell: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: 'rgba(47, 43, 61, 0.7)',
  },
  itemName: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#404040',
    letterSpacing: 0.3,
  },
  divider: {
    height: 1,
    backgroundColor: '#ddd',
    marginVertical: 16,
    marginHorizontal: 5,
  },
  totalsSection: {
    alignItems: 'flex-end',
    paddingRight: 10,
    marginBottom: 12,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 160,
  },
  totalLabel: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#404040',
    letterSpacing: 0.3,
    lineHeight: 24,
  },
  totalValue: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: 'rgba(47, 43, 61, 0.7)',
    letterSpacing: 0.3,
    lineHeight: 24,
  },
  balanceDueContainer: {
    backgroundColor: '#606060',
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 6,
    alignSelf: 'flex-end',
    width: 181,
  },
  balanceDueLabel: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#fff',
    letterSpacing: 0.3,
    lineHeight: 24,
  },
  balanceDueValue: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    color: '#fff',
    letterSpacing: 0.3,
    lineHeight: 24,
  },
  deliverySection: {
    paddingHorizontal: 30,
    marginBottom: 32,
  },
  deliverySectionTitle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 13,
    color: '#444',
    letterSpacing: 0.3,
    marginBottom: 16,
  },
  deliveryDropdown: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    paddingVertical: 8,
  },
  deliveryText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#404040',
    letterSpacing: 0.3,
  },
  deliveryPlaceholder: {
    color: '#404040',
  },
  deliveryOptions: {
    marginTop: 8,
  },
  deliveryOption: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  deliveryOptionText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    color: '#404040',
  },
  paymentSection: {
    marginTop: 8,
    marginBottom: 8,
  },
  paymentTitle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 13,
    color: '#444',
    letterSpacing: 0.3,
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  paymentOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 15,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
    marginHorizontal: 20,
  },
  paymentOptionRowSelected: {
    borderColor: '#099453',
    backgroundColor: '#f7fdf9',
  },
  paymentOptionCardDisabled: {
    opacity: 0.5,
    backgroundColor: '#f5f5f5',
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#ddd',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  radioOuterSelected: {
    borderColor: '#099453',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#099453',
  },
  paymentTextContainer: {
    flex: 1,
  },
  paymentLenderName: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    color: '#101010',
    lineHeight: 18,
  },
  paymentLenderSubtitle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#979797',
    marginTop: 2,
    lineHeight: 17,
  },
  paymentLenderAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#4A3FD1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentLenderAvatarText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    lineHeight: 34,
    width: '100%',
    includeFontPadding: false,
    textAlignVertical: 'center',
    textAlign: 'center',
    color: '#fff',
  },
  bottomContainer: {
    paddingHorizontal: 40,
    paddingVertical: 20,
    backgroundColor: '#fff',
    marginTop: 20,
  },
});
