import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F8FB' },
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 24 },
  content: { paddingHorizontal: 24, paddingBottom: 24 },
  card: {
    marginTop: 1,
    borderRadius: 40,
    backgroundColor: '#FFFFFF',
    shadowColor: '#6d6d6d',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
    paddingBottom: 16,
    overflow: 'hidden',
  },
  sectionHeader: {
    alignSelf: 'stretch',
    backgroundColor: '#E7F8F0',
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  sectionTitle: { lineHeight: 22, color: '#101010', fontSize: 14, fontWeight: '600' },
  text: { color: '#000000', fontSize: 12, lineHeight: 16 },
  row: { 
    flexDirection: 'row', 
    alignItems: 'flex-start', 
    paddingVertical: 3,
  },
  label: { 
    width: '58%', 
    color: '#2F2B3DB2', 
    fontSize: 12, 
    fontWeight: '500',
    lineHeight: 18,
  },
  value: { 
    width: '42%', 
    color: '#2F2B3DB2', 
    fontSize: 12, 
    fontWeight: '500',
    lineHeight: 18,
  },
  lableWrapper: { paddingHorizontal: 20, paddingVertical: 8 },
  pdfCard: {
    marginTop: 26,
    borderWidth: 4,
    borderColor: '#D8D8DC',
    borderRadius: 20,
    padding: 8,
    backgroundColor: '#FFFFFF',
  },
  pdf: { width: '100%', height: 600, borderRadius: 12},
  downloadText: { marginTop: 23, alignSelf: 'center', color: '#101010', fontSize: 14, fontWeight: '500', textDecorationLine: 'underline' },
  consentWrap: { flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 40  },
  consentIconWrap: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#099453', alignItems: 'center', justifyContent: 'center' },
  consentText: { color: '#8B8B8B', fontSize: 14, fontStyle: 'italic', lineHeight: 18 },
  consentTextWrap: { flex: 1, width: '80%' },
  consentTextLink: { color: '#099453', textDecorationLine: 'underline' },
  ctaWrap: { marginTop: 30, alignSelf: 'stretch', backgroundColor: '#099453', borderRadius: 12, paddingVertical: 18, paddingHorizontal: 80 },
  ctaLabel: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', textAlign: 'center' },
  saveButton: { marginTop: 40, alignSelf: 'stretch', marginHorizontal: 20 },

  executeFsaSection: {
    marginTop: 24,
    backgroundColor: '#E7F8F0',
    borderRadius: 12,
    padding: 20,
  },
  executeFsaDesc: {
    fontSize: 13,
    color: '#404040',
    lineHeight: 18,
    marginBottom: 16,
  },
  executeFsaDetail: {
    fontSize: 12,
    color: '#404040',
    lineHeight: 18,
    marginBottom: 4,
  },
  executeFsaDetailLabel: {
    fontSize: 12,
    color: '#101010',
    fontWeight: '600',
    lineHeight: 18,
  },
  executeFsaButton: {
    backgroundColor: '#099453',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 16,
  },
  executeFsaButtonText: {
    fontSize: 14,
    color: '#FFFFFF',
    lineHeight: 20,
  },
});
