import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F8FB' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
  },
  title: { color: '#101010', fontSize: 18, fontWeight: '600' },
  content: { paddingHorizontal: 24, paddingBottom: 24 },
  card: {
    marginTop: 18,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#6d6d6d',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  stepsWrap: { marginHorizontal: 12 },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  badge: {
    backgroundColor: '#1D3A70',
    borderRadius: 5,
    paddingVertical: 9,
    paddingHorizontal: 7,
  },
  cardTitle: { fontSize: 13, color: '#101010', fontWeight: '600' },
  desc: { marginTop: 11, fontSize: 13, color: '#404040', opacity: 0.6 },
  facilityRow: {
    flexDirection: 'row',
    gap: 25,
    marginTop: 24,
    alignItems: 'flex-start',
  },
  facilityImg: {
    width: 187,
    height: 120,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  facilityLabel: { fontSize: 13, color: '#979797', fontWeight: '500' },
  facilityType: { fontSize: 15, color: '#404040', fontWeight: '600' },
  changeLink: {
    marginTop: 17,
    fontSize: 10,
    color: '#099453',
    textDecorationLine: 'underline',
  },
  sectionLabel: {
    marginTop: 24,
    fontSize: 15,
    color: '#404040',
    fontWeight: '600',
  },
  checkboxCard: { paddingVertical: 12, borderRadius: 8 },
  tenureRow: { flexDirection: 'row', gap: 8, marginTop: 12, flexWrap: 'wrap' },
  chip: {
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  chipActive: { backgroundColor: '#09945333', borderColor: '#09945333' },
  chipText: { fontSize: 13, color: '#404040', fontWeight: '600' },
  checkboxList: { marginTop: 24 },
  descriptionInput: { marginBottom: 0 },
  descriptionBox: {
    borderWidth: 0,
    backgroundColor: '#F8F8FB',
    borderRadius: 0,
    paddingHorizontal: 18,
    // paddingVertical: 18,
    minHeight: 96,
  },
  descriptionText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    color: '#404040',
    lineHeight: 18,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 24,
  },

  nextButton: { marginTop: 24, alignSelf: 'stretch' },
});
