import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F8FB',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 16,
    zIndex: 1,
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: '#101010',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
  },
  markAllButton: {
    position: 'absolute',
    right: 16,
    zIndex: 1,
    padding: 4,
  },
  markAllText: {
    fontSize: 11,
    color: '#099453',
    fontFamily: 'Poppins-Medium',
  },
  tabContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#DDD',
    marginHorizontal: 16,
    height: 36,
    marginTop: 8,
    marginBottom: 8,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 28,
    borderRadius: 30,
    marginHorizontal: 4,
  },
  tabActive: {
    backgroundColor: '#099453',
  },
  tabText: {
    fontSize: 13,
    color: '#444',
    textAlign: 'center',
    lineHeight: 20,
  },
  tabTextActive: {
    color: '#FFFFFF',
  },
  listContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginHorizontal: 10,
    marginTop: 4,
    paddingVertical: 4,
    flex: 1,
  },
  notificationCard: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    paddingVertical: 14,
  },
  unreadCard: {
    backgroundColor: '#F8F8FB',
  },
  readCard: {
    backgroundColor: '#FFFFFF',
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E7F8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  dotIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    position: 'absolute',
    left: 29,
    bottom: -2,
  },
  unreadDot: {
    backgroundColor: '#099453',
  },
  readDot: {
    backgroundColor: '#B0B0B0',
  },
  contentContainer: {
    flex: 1,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  notificationTitle: {
    fontSize: 13,
    lineHeight: 15,
    letterSpacing: 0.3,
    color: '#1D1D1D',
    fontFamily: 'Poppins-Regular',
    flex: 1,
    marginRight: 8,
  },
  unreadTitle: {
    fontFamily: 'Poppins-Bold',
    color: '#1D1D1D',
  },
  readTitle: {
    fontFamily: 'Poppins-Regular',
    color: '#404040',
  },
  badge: {
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: '#099453',
  },
  badgeText: {
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.1,
    color: '#FFFFFF',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'right',
  },
  notificationBody: {
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.1,
    color: '#404040',
    opacity: 0.6,
    fontFamily: 'Poppins-Medium',
    marginBottom: 8,
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeText: {
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.1,
    color: '#404040',
    opacity: 0.6,
    fontFamily: 'Poppins-MediumItalic',
    fontStyle: 'italic',
    marginLeft: 4,
  },
  separator: {
    height: 1,
    backgroundColor: '#DDDDDD',
    marginHorizontal: 15,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 14,
    color: '#898A8D',
    fontFamily: 'Poppins-Medium',
  },
});
