import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F8FB' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  title: { color: '#101010', fontSize: 18, fontWeight: '600' },
  content: { paddingHorizontal: 24, paddingBottom: 24 },
  stepsWrap: {
    marginTop: 18,
    marginHorizontal: 14,
  },
  card: {
    marginTop: 38,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#6d6d6d',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  cardTitle: { fontSize: 13, color: '#101010', fontWeight: '600' },
  checkBadge: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#E7F8F0', alignItems: 'center', justifyContent: 'center' },
  row: { marginTop: 14 },
  rowLabel: { fontSize: 13, color: '#444444' },
  rowValue: { marginTop: 8, fontSize: 14, color: '#101010', fontWeight: '500' },
  rowInputContainer: { marginTop: 8, marginBottom: 0 },
  rowInputWrapper: { paddingVertical: 6, paddingBottom: 6 },
  rowInput: { fontSize: 14, color: '#101010' },
  divider: { marginTop: 12, height: 1, backgroundColor: '#F5F5F5' },
  pickerDivider: { marginTop: 10, height: 1, backgroundColor: '#DDDDDD' },
  inlinePicker: { marginTop: 8 },
  residentCard: { marginTop: 24 },
  residentLabel: { marginTop: 20, fontSize: 13, color: '#444444', fontWeight: '500' },
  ownedWrap: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 },
  ownedBtn: { flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#DDDDDD', borderRadius: 5, backgroundColor: '#FFFFFF', paddingVertical: 8, paddingHorizontal: 13, width: 137, height: 40 },
  radioOuterActive: { borderWidth: 1, borderColor: '#099453', borderRadius: 50, backgroundColor: '#099453', padding: 4 },
  radioOuter: { borderWidth: 1, borderColor: '#DDDDDD', borderRadius: 50, backgroundColor: '#FFFFFF', padding: 4 },
  radioInner: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#FFFFFF' },
  ownedText: { color: '#898A8D', fontSize: 14, fontWeight: '500' },
  gpsLabel: { marginTop: 32, fontSize: 13, color: '#444444' },
  gpsAddonContainer: { width: 'auto', marginRight: 8 },
  requiredAsterisk: { color: '#F32735', marginLeft: 4 },
  declarationCard: { marginTop: 32, paddingVertical: 38 },
  declarationRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 40 },
  declarationQuestion: { width: '55%', fontSize: 14, color: '#444444', fontWeight: '500',  letterSpacing: 0.3, lineHeight: 22},
  linkInfo: { marginTop: 8, fontSize: 12, color: '#6a2a7f', fontWeight: '600' },
  confirmRow: { flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 40 },
  nextButton: { marginTop: 40, alignSelf: 'stretch', marginHorizontal: 20 },
});

