import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F8FB' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  title: { color: '#101010', fontSize: 18, fontWeight: '600' },
  content: { paddingHorizontal: 24, paddingBottom: 24 },
  stepsWrap: {
    marginTop: 18,
    marginHorizontal: 14,
  },
  card: {
    marginTop: 32,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#6d6d6d',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
    paddingHorizontal: 20,
    paddingVertical: 32,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  cardTitle: { fontSize: 13, color: '#101010', fontWeight: '600' },
  editLink: { fontSize: 13, color: '#099453', fontWeight: '600', textDecorationLine: 'underline' },
  row: { marginTop: 16 },
  rowLabel: { fontSize: 13, color: '#444444' },
  rowValue: { marginTop: 8, fontSize: 14, color: '#101010', fontWeight: '500' },
  divider: { marginTop: 12, height: 1, backgroundColor: '#DDDDDD' },
  addFarmRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 24 },
  addFarmCircle: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#099453', alignItems: 'center', justifyContent: 'center' },
  addFarmText: { fontSize: 14, color: '#101010', fontWeight: '500' },
  nextButton: { marginTop: 40, alignSelf: 'stretch', marginHorizontal: 24 },
  radioWrap: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 },
  radioBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: '#DDDDDD', borderRadius: 5, backgroundColor: '#FFFFFF', paddingVertical: 8, paddingHorizontal: 13, width: 137, height: 40 },
  radioOuterActive: { borderWidth: 1, borderColor: '#099453', borderRadius: 50, backgroundColor: '#099453', padding: 4 },
  radioOuter: { borderWidth: 1, borderColor: '#DDDDDD', borderRadius: 50, backgroundColor: '#FFFFFF', padding: 4 },
  radioInner: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: '#FFFFFF' },
  radioText: { color: '#898A8D', fontSize: 14, fontWeight: '500' },
  collapsedCard: {
    marginTop: 20,
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#6d6d6d',
    shadowOpacity: 0.18,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
    elevation: 2,
  },
  collapsedIndicator: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  collapsedIndicatorInner: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#DDDDDD' },
  collapsedGps: { flex: 1, marginLeft: 12, fontSize: 14, color: '#101010', fontWeight: '500' },
  collapsedArrow: { marginLeft: 12 },
});

