import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F8FB' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  title: { color: '#101010', fontSize: 18, fontWeight: '600' },
  content: { paddingHorizontal: 24, paddingBottom: 24 },
  stepsWrap: { marginTop: 18, marginHorizontal: 14 },
  card: {
    marginTop: 32,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#6d6d6d',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  cardTitle: { fontSize: 13, color: '#101010', fontWeight: '600' },
  infoBadge: { width: 18, height: 18, borderRadius: 9, backgroundColor: '#11AA64', alignItems: 'center', justifyContent: 'center' },
  infoText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  row: { marginTop: 22 },
  lenderLabel: { color: '#444444' },
  rowLabel: { fontSize: 13, color: '#444444' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginTop: 12 },
  produceTile: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 9,
    width: 150,
    height: 60,
    gap: 10,
  },
  produceTileSelected: { backgroundColor: '#09945333', borderColor: 'transparent' },
  produceCircle: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, borderColor: '#DDDDDD', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  produceLabel: { fontSize: 13, color: '#404040', fontWeight: '500' },
  divider: { marginTop: 12, height: 1, backgroundColor: '#DDDDDD' },
  inlineRow: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 16 },
  inlineLeft: { flex: 1, marginRight: 12 },
  inlineRight: { flex: 1 },
  pickerDivider: { marginTop: 10, height: 1, backgroundColor: '#DDDDDD' },
  inlinePicker: { borderBottomWidth: 1, borderBottomColor: '#DDDDDD', borderWidth: 1 },
  nextButton: { marginTop: 40, alignSelf: 'stretch', marginHorizontal: 24 },
  image254: { width: 26, height: 26 },
  image253: { width: 27, height: 27 },
  image255: { width: 28, height: 28 },
  image259: { width: 32, height: 32 },
  image257: { width: 28, height: 28 },
  image258: { width: 26, height: 26 },
  image260: { width: 26, height: 26 },
  image261: { width: 28, height: 28 },
});
