import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 30,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 40,
  },
  backButton: {
    marginRight: 16,
  },
  headerSpacer: {
    width: 24,
  },
  title: {
    fontSize: 18,
    lineHeight: 22,
    color: '#101010',
    textAlign: 'center',
    flex: 1,
    fontFamily: 'Poppins-SemiBold',
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 20,
    color: '#404040',
    opacity: 0.6,
    letterSpacing: 0.1,
    marginBottom: 37,
    fontFamily: 'Poppins-Medium',
  },
  approvalBanner: {
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#2E7D32',
  },
  approvalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  checkMarkIcon: {
    width: 20,
    height: 20,
  },
  approvalTitle: {
    color: '#1B5E20',
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Poppins-SemiBold',
  },
  approvalNote: {
    color: '#1B5E20',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Poppins-Medium',
  },
  rejectionBanner: {
    backgroundColor: '#FFEBEE',
    borderRadius: 10,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#D32F2F',
  },
  rejectionTitle: {
    color: '#C62828',
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 8,
    fontFamily: 'Poppins-SemiBold',
  },
  rejectionNote: {
    color: '#C62828',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Poppins-Medium',
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: 10,
    padding: 20,
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionIconBox: {
    width: 30,
    height: 30,
    backgroundColor: '#1D3A70',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  sectionTitle: {
    fontSize: 13,
    lineHeight: 18,
    color: '#101010',
    fontFamily: 'Poppins-SemiBold',
  },
  sectionContent: {
    marginLeft: 0,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: 7,
    marginBottom: 7,
    gap: 8,
  },
  summaryRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#DDDDDD',
  },
  summaryRowLabel: {
    fontSize: 13,
    lineHeight: 18,
    color: '#5E5E5E',
    fontFamily: 'Poppins-Medium',
    flex: 1,
    flexShrink: 1,
  },
  summaryRowValueContainer: {
    flex: 1,
    flexShrink: 1,
    alignItems: 'flex-end',
    maxWidth: '50%',
  },
  summaryRowValue: {
    fontSize: 13,
    lineHeight: 18,
    color: '#5E5E5E',
    textAlign: 'right',
    fontFamily: 'Poppins-Medium',
  },
  addFarmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 8,
  },
  addFarmText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#101010',
    letterSpacing: 0.3,
    fontFamily: 'Poppins-Medium',
  },
  requestLoanButton: {
    marginTop: 30,
    marginBottom: 20,
  },
});

