import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  content: { paddingHorizontal: 20, paddingBottom: 24 },
  searchWrap: { marginTop: 16 },
  bannerWrap: {
    marginTop: 20,
    alignItems: 'center'
  },
  bannerCard: {
    width: '100%',
    height: 180,
    borderRadius: 12,
    backgroundColor: '#1D3A70',
    position: 'relative',
    overflow: 'hidden',
  },
  bannerTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '500', marginTop: 10 },
  bannerSub: { color: '#BFBFBF', fontSize: 12, fontStyle: 'italic', marginTop: 5, width: 165 },
  sectionTitle: { marginTop: 32, marginLeft: 9, color: '#1D3A70', fontSize: 16, fontWeight: '600' },
  sectionSub: { marginLeft: 9, color: '#444444', fontSize: 12 },
  listWrap: { marginTop: 16 },
  horizontalContent: { paddingHorizontal: 9 },
  card: {
    width: 202,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: 12,
    overflow: 'hidden',
  },
  separator: { width: 12 },
  cardImage: { width: '100%', height: 106 },
  cardContent: { padding: 9 },
  cardTitle: { color: '#444444', fontSize: 12 },
  cardMeta: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
  cardMetaText: { color: '#888888', fontSize: 11, fontWeight: '500', marginLeft: 6 },
  viewMoreBtn: {
    marginTop: 16,
    marginHorizontal: 9,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EAEAEA',
    borderRadius: 12,
    paddingVertical: 6,
  },
  viewMoreText: { color: '#444444', fontSize: 12, fontWeight: '500' },
  moreCard: {
    position: 'relative',
    borderWidth: 1,
    borderColor: '#EAEAEA',
    borderRadius: 8,
    padding: 11,
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
    marginRight: 8,
  },
  bestPriceBadge: {
    position: 'absolute',
    top: 70,
    right: -6,
    width: 121,
    height: 34,
    resizeMode: 'contain',
  },
  moreCardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  moreImage: { width: 92, height: 92, borderRadius: 6 },
  moreContent: { flex: 1, marginLeft: 12, marginTop: 2 },
  moreTitle: { color: '#444444', fontSize: 14, fontWeight: '600' },
  moreMeta: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
  moreMetaText: { color: '#444444', fontSize: 12, fontWeight: '500', marginLeft: 6 },
  dealsRowHeader: { marginTop: 13 },
  dealsLabel: { color: '#BCBCBC', fontSize: 10, fontWeight: '500' },
  dealsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  tag: { backgroundColor: '#B2E1C3', borderRadius: 2, paddingVertical: 4, paddingHorizontal: 8 },
  tagText: { color: '#444444', fontSize: 10, fontWeight: '500' },
  verticalListWrap: { marginTop: 16 },
});
