import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F8FB' },
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 24 },
  content: { paddingHorizontal: 24, paddingBottom: 24 },
  card: {
    marginTop: 1,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#6d6d6d',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
    paddingTop: 31,
    paddingBottom: 10,
    paddingHorizontal: 20,
    zIndex: 1,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20, zIndex: 10 },
  badge: { backgroundColor: '#1D3A70', borderRadius: 5, padding: 5, alignItems: 'center', justifyContent: 'center' },
  cardTitle: { fontSize: 13, color: '#101010', fontWeight: '600', marginLeft: 8 },
  fieldsRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginTop: 24 },
  fieldWrap: { width: '48%' },
  fieldLabel: { fontSize: 13, color: '#444444', fontWeight: '500' },
  fieldValue: { marginTop: 12, lineHeight: 22, letterSpacing: 0.3, color: '#404040', fontSize: 14, fontWeight: '600' },
  fieldDisabled: { color: '#EDEDED' },
  line: { marginTop: 12, backgroundColor: '#DDDDDD', width: '100%', height: 1 },
  inlineRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  inlineLeft: { flex: 1, marginRight: 12 },
  inlineRight: { flex: 1 },
  inlinePicker: { borderBottomWidth: 1, borderBottomColor: '#DDDDDD', borderWidth: 1 },
  nextButton: { marginTop: 32, alignSelf: 'stretch' },
  tooltipBox: { position: 'absolute', width: 167 },
  errorText: { fontSize: 12, color: '#D32F2F', marginTop: 4, marginLeft: 2 },
  produceBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#09945333',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 24,
    gap: 12,
  },
  produceIcon: {
    width: 32,
    height: 32,
  },
  produceText: {
    fontSize: 16,
    color: '#404040',
  },
});
