import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F8FB',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#101010',
    fontSize: 18,
    lineHeight: 22,
    fontFamily: 'Poppins-SemiBold',
    marginRight: 24, // Balance the back button on left
  },
  listContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginHorizontal: 10,
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  scrollContent: {
    gap: 20,
    paddingBottom: 20,
  },
  // Offer Card
  offerCardWrapper: {
    marginLeft: 3, // account for shadow extending left
  },
  offerCard: {
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    overflow: 'visible',
    position: 'relative',
  },
  offerCardShadow: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: -3,
    right: 0,
    backgroundColor: '#1D3A70',
    borderRadius: 20,
    zIndex: -1,
  },
  offerCardShadowAccepted: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: -3,
    right: 0,
    backgroundColor: '#099453',
    borderRadius: 20,
    zIndex: -1,
  },
  offerCardShadowRejected: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: -3,
    right: 0,
    backgroundColor: '#DEDEDE',
    borderRadius: 20,
    zIndex: -1,
  },
  bankNameBanner: {
    backgroundColor: '#1D3A70',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    paddingVertical: 6,
    paddingHorizontal: 16,
    alignSelf: 'center',
    width: 200,
    alignItems: 'center',
  },
  bankNameText: {
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 16,
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
  },
  offerDetailsContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 10,
  },
  offerDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  offerDetailLabel: {
    color: 'rgba(47, 43, 61, 0.7)',
    fontSize: 12,
    lineHeight: 22,
    fontFamily: 'Poppins-Medium',
  },
  offerDetailValue: {
    color: 'rgba(47, 43, 61, 0.7)',
    fontSize: 12,
    lineHeight: 22,
    fontFamily: 'Poppins-Medium',
    textAlign: 'right',
  },
  viewDetailsButton: {
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: 12,
    height: 45,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: 220,
    marginBottom: 16,
  },
  viewDetailsButtonAccepted: {
    backgroundColor: '#1D3A70',
    borderRadius: 12,
    height: 45,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: 220,
    marginBottom: 16,
  },
  viewDetailsText: {
    color: '#099453',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'Poppins-SemiBold',
    marginLeft: 8,
  },
  viewDetailsTextAccepted: {
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'Poppins-SemiBold',
    marginLeft: 8,
  },
  acceptedBadge: {
    position: 'absolute',
    top: 6,
    right: 10,
    zIndex: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F8FB',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    color: '#898A8D',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'Poppins-Medium',
  },
});
